name: cocktail_app
description: Cocktail of the day application
version: 1.0.0+1
authors:
  - Flutter Mobile developer cource

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.1
  flutter_redux: ^0.7.0
  redux_thunk: ^0.3.0
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.1
  json_serializable: ^3.4.1
  freezed: ^0.12.3

flutter:
  uses-material-design: true

