name: cocktail
description: Dart Async lesson
version: 0.0.1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  http: ^0.12.2
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

  build_runner: ^1.10.1
  json_serializable: ^3.4.1

flutter:
  assets:
    - assets/images/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Ultralight.ttf
          weight: 200
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700 
  uses-material-design: true