name: cocktail
description: Dart Async lesson
version: 0.0.1

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  json_annotation: ^3.0.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.1
  json_serializable: ^3.4.1

flutter:
  assets:
    - ./assets/search.svg