name: lesson_17
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  http: ^0.12.2
  flutter_bloc: ^6.1.1
  hydrated_bloc: ^6.1.0
  replay_bloc: ^0.0.1-dev.4
  provider: any
  built_collection: ^4.3.2


dev_dependencies:
  build_runner: ^1.10.1
  pedantic: ^1.9.0
  json_serializable: ^3.4.1

flutter:
  uses-material-design: true