name: lesson_16
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  http: ^0.12.2
  provider: ^4.3.2+2
  path_provider: ^1.6.24
  get_it: ^5.0.1
  injectable: ^1.0.5
  shared_preferences: any

dev_dependencies:
  build_runner: ^1.10.1
  pedantic: ^1.9.0
  json_serializable: ^3.4.1
  injectable_generator: any

flutter:
  uses-material-design: true